version: "2"
services:
    web:
        container_name: web-container
        restart: always
        build:
            context: ./
            dockerfile: web-dockerfile.txt
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./webserver/:/webserver/
        networks:
            - default