version: "2"
services:
    mssql:
        container_name: mssql-container
        image: microsoft/mssql-server-linux:latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: yourStrong(!)Password
            MSSQL_PID: Express
        networks:
            - default
        links:
            - web
        volumes:
            - ./webserver/:/webserver/
            - ./webserver/data/mssql:/var/opt/mssql