version: "2"
services:
    oracle:
        container_name: oracle-container
        image: sath89/oracle-12c
        ports:
            - "8080:8080"
            - "1521:1521"
        environment:
            DBCA_TOTAL_MEMORY: 1024
        networks:
            - default
        links:
            - web
        volumes:
            - ./webserver/:/webserver/
            - ./webserver/data/oracle:/u01/app/oracle