version: "2"
services:
    postgres:
        container_name: postgres-container
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: 123456
        networks:
            - default
        links:
            - web
        volumes:
            - ./webserver/:/webserver/
            - ./webserver/data/postgres:/var/lib/postgresql/data