version: "2"
services:
    db2:
        container_name: db2-container
        image: ibmcom/db2express-c:latest
        ports:
            - "50000:50000"
        environment:
            DB2INST1_PASSWORD: db2inst1-pwd
            LICENSE: accept
        networks:
            - default
        links:
            - web
        volumes:
            - ./webserver/:/webserver/
            - ./webserver/data-db2:/share