version: "2"
services:
    web:
        container_name: web-container
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./webserver/:/webserver/
        networks:
            - default
    db:
        container_name: db-container
        image: mariadb:latest
        command: --max_allowed_packet=32505856 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        
        # comando para não dar pau em mapear um diretório windows no linux com o mariadb
        command: 'mysqld --innodb-flush-method=fsync'
        
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: teste
            MYSQL_USER: local
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - default
        volumes:
            - ./webserver/:/webserver/
            - ./webserver/database-data:/var/lib/mysql