version: "2"
services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./webserver/:/webserver/
        networks:
            - default
    db:
        image: mariadb:latest
        command: --max_allowed_packet=32505856 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: teste
            MYSQL_USER: local
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - default
        volumes:
            - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: