version: "2"
services:
    mariadb:
        container_name: mariadb-container
        image: mariadb:latest
        command: --max_allowed_packet=32505856 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        
        # comando para não dar pau em mapear um diretório windows no linux com o mariadb
        command: 'mysqld --innodb-flush-method=fsync'
        
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: teste
            MYSQL_USER: local
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - default
        links:
            - web
        volumes:
            - ./webserver/:/webserver/
            - ./webserver/data/mariadb:/var/lib/mysql
            - ./webserver/data/mariadb-config:/etc/mysql/conf.d
            #- C:\docker-webserver\webserver:/webserver/
            #- C:\docker-webserver\webserver\data\mariadb:/var/lib/mysql          