# Possíveis problemas
# 1) Se não conseguir compartilhar o driver com o Docker, verifique se no Windows esta habilitado o compartilhamento de 
# arquivos SMB/CIFS 1.0
# 2) Se ocorrer erro na montagem do volume, tente informar o caminho absoluto do diretório no host
# 3) Libere as permissões do diretório no qual esta tentando montar o volume
version: "2"
services:
    web:
        container_name: web-container
        #restart: always
        build:
            context: ./
            dockerfile: webserver.Dockerfile
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
            - "3001:3001"
        volumes:
            #- ./webserver/:/webserver/
            - C:\docker-webserver\webserver\:/webserver/
        networks:
            - default